name: Post to MS Teams on Feature Commit

on:
  push:
    branches:
      - main  # Change as needed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: startsWith(toLower(github.event.head_commit.message), 'feat:')

    steps:
      - name: Post to MS Teams
        env:
          WEBHOOK_URL: ${{ secrets.MS_TEAMS }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d @- "$WEBHOOK_URL" <<EOF
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "GitHub Feature Commit Update",
            "sections": [
              {
                "activityTitle": "🚀 Feature Commit",
                "facts": [
                  { "name": "Repository", "value": "${{ github.repository }}" },
                  { "name": "Committed by", "value": "${{ github.event.head_commit.author.name }}" },
                  { "name": "Commit Message", "value": "${{ github.event.head_commit.message }}" },
                  { "name": "Commit SHA", "value": "${{ github.sha }}" }
                ],
                "markdown": true
              }
            ]
          }
